### ISSUE TITLE
Wrong directory slash direction under windows

### ISSUE THREAD

**Issue by dice14u** [Samsung/react-native-tizen-dotnet#10]
https://github.com/Samsung/react-native-tizen-dotnet/blob/434d338796bed36dc7024f3daa04d217d7e33d99/Devtools/react-native-tizen-dotnet/src/prebuild.js#L7

Does not work while running under windows as "dir" has \ instead of /

**Comment by sutaking** [comment]
thank your for your message.
we will fix it ASAP :)

**Comment by sutaking** [comment]
can you try again? with v0.1.4
