### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by gorhgorh** [Samsung/react-native-tizen-dotnet#17]
Hi there, I was just wondering the state of this project as I'm convidering available technologies to make some app for galaxy watches.

Thanks

**Comment by sutaking** [comment]
Hi,
react-native-tizen-dotnet project deps dotnet sdk, and it seems also release on wearable Tizen Platfrom.
But it still some deps libs not release on Tizen Watch(like JSCore, Yoga)

**Comment by gorhgorh** [comment]
hello @sutaking,thanks for the answer. 
That was my initial guess as well, but i wanted to be sure about it.

i'll close this then
