### ISSUE TITLE
Support running in emulator.

### ISSUE THREAD

**Issue by maomao9003** [Samsung/react-native-tizen-dotnet#18]
We should support react-native-tizen can run in emulator.
* Provice JSCore can running in elmulator.

**Comment by maomao9003** [comment]
The JSCore and yoga library for emulator has been uploaded:
Framework/ReactNet/JSCore/libJSCore_i586.so
Framework/ReactNet/yoga/libyoga_i586.so

If developer want running react-native-tizen project in emulator, can use those i586 libraries instead the libraries in project.

@sutaking Let's consider provide specific command to package a emulator runable tpk?

**Comment by indapublic** [comment]
Could you explain where I can find those files:
`Framework/ReactNet/JSCore/libJSCore_i586.so`
`Framework/ReactNet/yoga/libyoga_i586.so`

**Comment by maomao9003** [comment]
@indapublic you can find it in repos:
https://github.com/Samsung/react-native-tizen-dotnet/blob/master/Framework/ReactNet/JSCore/libJSCore_i586.so
https://github.com/Samsung/react-native-tizen-dotnet/blob/master/Framework/ReactNet/yoga/libyoga_i586.so
