### ISSUE TITLE
npm run package command results in error

### ISSUE THREAD

**Issue by ashwanikumar415** [Samsung/react-native-tizen-dotnet#21]
Followed the simple steps mentioned in page :
But running npm run package gives below error

`[Wed Jul 17 2019 19:46:47 GMT+0530 (India Standard Time)][Util][INFO]: App current path : C:\eDrive\ThingsLearnt\TizenApps\ReactNativeWithDotNet\myTizenApp\
[Wed Jul 17 2019 19:46:47 GMT+0530 (India Standard Time)][Util][INFO]: App Name : myTizenApp
[Wed Jul 17 2019 19:46:47 GMT+0530 (India Standard Time)][Util][INFO]: Loading config file from : C:\eDrive\ThingsLearnt\TizenApps\ReactNativeWithDotNet\myTizenApp\package.json
[Wed Jul 17 2019 19:46:47 GMT+0530 (India Standard Time)][Package][INFO]: Command: build project with dotnet SDK
[Wed Jul 17 2019 19:46:47 GMT+0530 (India Standard Time)][Package][INFO]: Tizen dotnet Project Path: C:\eDrive\ThingsLearnt\TizenApps\ReactNativeWithDotNet\myTizenApp\/Tizen
[Wed Jul 17 2019 19:46:47 GMT+0530 (India Standard Time)][Package][INFO]: local ReactNativeTizen.dll sha1 hash check: e295ff62c9aa2bd0cc8aca188e206e3b2a82f985
[Wed Jul 17 2019 19:46:47 GMT+0530 (India Standard Time)][Package][INFO]: The latest version of ReactNativeTizen.dll is e295ff62c9aa2bd0cc8aca188e206e3b2a82f985
'dotnet' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:656
    throw err;
    ^

Error: Command failed: dotnet restore  C:\eDrive\ThingsLearnt\TizenApps\ReactNativeWithDotNet\myTizenApp\Tizen
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at packagerBuild (C:\eDrive\ThingsLearnt\TizenApps\ReactNativeWithDotNet\myTizenApp\node_modules\react-native-tizen-dotnet\build\package.js:45:33)
    at Object.<anonymous> (C:\eDrive\ThingsLearnt\TizenApps\ReactNativeWithDotNet\myTizenApp\node_modules\react-native-tizen-dotnet\build\package.js:48:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)`

**Comment by maomao9003** [comment]
Hi,
This error caused by missing .NET Core SDK:
**'dotnet' is not recognized as an internal or external command,**

Please install [.NET Core SDK](https://dotnet.microsoft.com/download) in your PC.

Thanks for your feedback!

**Comment by ashwanikumar415** [comment]
@maomao9003  
Thanks for your quick help sample app is running properly on Tizen TV.
Since am not a .Net developer I did not have .NET Core SDK and faced that error.
There can be many react native developers like me having this issue. 
Can installing .NET Core SDK be added as a step to document page? if not added already by the developer.
"Getting Started" section is already easy to follow. Just adding installing .NET Core SDK (if not already installed) point will avoid googling by others :)

**Comment by sutaking** [comment]
@ashwanikumar415 
Thx for your reply, we will update our Guide for that

**Comment by maomao9003** [comment]
Has add guide in this commit before:
[#21 Add "Installing dependencies".](https://github.com/Samsung/react-native-tizen-dotnet/commit/e6b58efb60c17e81f240a793501cd92e360feb0c)
