### ISSUE TITLE
<image> component inside render loads blurry image , if src = "<some external link>"

### ISSUE THREAD

**Issue by ashwanikumar415** [Samsung/react-native-tizen-dotnet#22]
Am using image component,  as mentioned in info pages: http://metadata.vodip.virtua.com.br/posters/vod_posters/PosterResized_d3ea7e95-b64d-4274-970c-2daf8da7c562-poster.jpg?max-width=204&max-height=285 

But image gets rendered blurry on Tizen Samsung TV . 
Using image component like below 
`        <Image
          style={{width: 50, height: 50}}
          source={{uri: url}}
        />`
where `url = https://facebook.github.io/react-native/img/tiny_logo.png` 

Any clue ? i tried resizeMode to contain and all of them . But still image is always blurry . not real image is shown . 
Is it required to load an image in componentDidMount() and save it as a blob and use it in render ?

**Comment by ashwanikumar415** [comment]
Actual Image : 
![actualImageForTizen](https://user-images.githubusercontent.com/7288437/64180465-71b0e700-ce82-11e9-9862-e341a9977c8c.jpg)



How tizen app loads it with above code : 

![imageComponentInTizen](https://user-images.githubusercontent.com/7288437/64180499-7fff0300-ce82-11e9-934a-f6483fb6c9fe.jpg)

**Comment by ashwanikumar415** [comment]
Is running tizen apps specific to samsung TV version or Tizen version ?
Is this issue could be because of that ? 
Below is my Samsung TV specifications : 
![tizenTV_version](https://user-images.githubusercontent.com/7288437/64407232-77d0de80-d0a1-11e9-8da3-442288bffa2a.jpg)

**Comment by maomao9003** [comment]
I tried it in Tizen 4.0 & Tizen 5.0.

Also same with your status... Need further check the reason.

**Comment by maomao9003** [comment]
@ashwanikumar415 
There is a [new change](https://github.com/Samsung/react-native-tizen-dotnet/commit/eed26cc1b9a1630da719497a08b5494b221cf6d3) fix this issue.

You can pull leatest code of react-native-tizen-dotnet. and follow these steps update ReactNativeTizen.dll in your app:
1. Jump into dir `react-native-tizen-dotnet/Framework/ReactNet/ReactNativeTizen`
2. Execute `dornet build`
3. Use generated `./bin/Debug/netstandard2.0/ReactNativeTizen.dll` replace `./Tizen/ReactNativeTizen.dll` in your app code
4. Repackage your app with `yarn package` and test.

If you have problem please tell me. Thanks for your finding a issue 👍

**Comment by ashwanikumar415** [comment]
Awesome :) worked beautifully 
Here onwards will this be part of every app I create using 
`npm i -g create-react-native-tizen-app`

??

**Comment by maomao9003** [comment]
If new ReactNativeTizen.dll released.
The new ReactNativeTizen.dll will in your new created app when using `create-react-native-tizen-app myTizenApp`

But new ReactNativeTizen.dll is not released now and there is no release plan now.
So please replace new ReactNativeTizen.dll manually. 😃
