### ISSUE TITLE
Unable to run in debug mode (package.json) : Shows below error 

### ISSUE THREAD

**Issue by ashwanikumar415** [Samsung/react-native-tizen-dotnet#23]
![TizenError](https://user-images.githubusercontent.com/7288437/64179878-7a54ed80-ce81-11e9-9936-e93b94456fde.jpg)

Steps followed :
1. Changed mode to "Debug" in package.json 
2. npm run bundle --dev
3. npm run package
4. npm run launch 

Launches the app with above screen.
PS : same steps if i do with "Release" mode runs the app successfully

**Comment by maomao9003** [comment]
hi, 

Please make sure launch debug server with `npm run server`, and config right debug server ip in app.

**Comment by maomao9003** [comment]
@ashwanikumar415 
What's your status of using debug mode.
