### ISSUE TITLE
Cannot set host ip in Debug mode on Tizen 5.5

### ISSUE THREAD

**Issue by panpawel88** [Samsung/react-native-tizen-dotnet#26]
Hello,

Your module uses internally the EcoreMainLoop class from ElmSharp package to dispatch some work to the main thread, see: https://github.com/Samsung/react-native-tizen-dotnet/blob/master/Framework/ReactNet/ReactNativeTizen/ElmSharp.Extension/EcoreLoopProxy.cs. It assumed that tasks are executed in FIFO order (first task scheduled, first task executed). However, EcoreMainLoop doesn't guarantee the execution order and recently they changed the behavior. On Tizen 5.5 all tasks scheduled from the main thread, are executed in LIFO order. See discussion: https://github.com/Samsung/TizenFX/issues/694#issuecomment-542184763

This modification affects the react-native-tizen-dotnet package. For example, please take a look at: https://github.com/Samsung/react-native-tizen-dotnet/blob/master/Framework/ReactNet/ReactNativeTizen/DevSupport/DevOptionDialog.cs

```
        private DevOptionDialog()
        {
            DispatcherHelpers.RunOnDispatcher(() =>
            {
                _popup = new Popup(ReactProgram.RctWindow)
                {

                };
                // ....
            });
        }

        public void Show()
        {
            DispatcherHelpers.RunOnDispatcher(() =>
            {
                _popup.Show();
                // ...
            });
        }
```

Typical usage would be:
```
var dialog = DevOptionDialog.GetInstance(); // calls DevOptionDialog constructor
dialog.Show();
```

If tasks are executed in FIFO order, then everything is fine: _popup field is created firstly and then method Show() is called. However, if tasks are executed in LIFO order, then Show() method is called before creating _popup field. This leads to NullReferenceException.

**Comment by maomao9003** [comment]
@ppaneksamsung  thanks for your patch! we can set host IP in Tizen5.5 now 😃
