### ISSUE TITLE
Can't debug on real TV or emulator

### ISSUE THREAD

**Issue by khanhqd** [Samsung/react-native-tizen-dotnet#28]
Thanks for amazing repo.
But I'm still stuck in debugging step. 
First, I try to launch app by command, but have same issue as: 
[https://github.com/Samsung/react-native-tizen-dotnet/issues/25#issue-495567856](url)

Then I try to release to .tpk file, and install to TV throw Device Manager, and this popup show:
<img width="1001" alt="Screen Shot 2019-11-01 at 00 46 32" src="https://user-images.githubusercontent.com/22678395/68008735-7a6f3f00-fcb2-11e9-818d-4d0790e95f37.png">

I had try disconnect and reconnect serveral time but it didn't work.
My TV has Tizen 4.0 Version

Please help me, thanks!

**Comment by indapublic** [comment]
Did you allow install apps for TV?

**Comment by maomao9003** [comment]
It's a TizenStudio issue. Maybe you need get some help from https://www.tizen.org/
