### ISSUE TITLE
Nothing readme for getting started

### ISSUE THREAD

**Issue by dice14u** [Samsung/react-native-tizen-dotnet#8]
Hey there,

I see that this repo isnt available in NPM and that is okay but a nice getting started readme would be good, something along the lines of git clone this repo locally, run blah bash script to export the built package, take the .tz file and install it on a tizen samsung tv and go.

**Comment by dice14u** [comment]
Also when using the created ReactNativeTizen.dll in visual studio with the Tizen 4.0 sdk it asks for the version 1 sdk to be referenced in the assembly but a google search of samsung.com and I cannot easily find a way to download Tizen.Net v 1.0.0.0

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'CoreUIApplication' is defined in an assembly that is not referenced. You must add a reference to assembly 'Tizen.Applications.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4aa249e9db245e88'.	NUITemplate1	C:\Users\dacross\source\repos\NUITemplate1\NUITemplate1\NUITemplate1.cs	12	Active
```

**Comment by maomao9003** [comment]
Thanks for your attention, submit "getting started readme" is our next plan.
please stay tuned.
